### ISSUE TITLE
Populate the "xarray-pickler" repo (from cookiecutter)

### ISSUE THREAD

**Issue by agstephens** [cedadev/xarray-pickler#1]
Set up the "xarray-pickler" package:
- [x] Create the "cedadev/xarray-pickler" public repo
- [x] Create the new package "cedadev/xarray-pickler" from the cedadev cookie-cutter template
- [x] Create the python package
- [x] Create a configuration system (like we use in `roocs`) that uses a default config file that can be overridden by a local config file
- [x] Create the unit tests
- [x] Create some basic documentation
- [x] Publish to PyPI

@ellesmith88 I have made a decision that we need this package (https://github.com/cedadev/xarray-pickler - already created as an empty repo) as a dependency of other work (such as general CEDA Intake catalogue maker(s)). I think the general features are as follows:

## Configuration

The following configuration options should be available:

```
[config_data_types]
booleans = use_cftime

[open_mfdataset_kwargs]
use_cftime = True
combine = by_coords

[...something about mapping / caching paths...]
needs a sensible way/place to put pickle files - should they be in the archive? or under /badc/<x>/metadata/xarray-pickles/ ???
```

## Python functionality

From the user perspective the code just needs to be:

```
from xarray_pickler import open_dset

dset_dir = '/badc/..../..../v2021010'

kwargs = {'parallel': True} 
ds = open_dset(dset_dir, **kwargs)
```

Behind the scenes we need something that can do:

```

def _get_pickle_path(dpath):
    ....needs to use some nice mapping and config info...
    ...not sure what to do here yet...
    ...maybe use something like: https://github.com/roocs/dachar/blob/d09b658f6d3cbcfc07c6c64939398ded79cd93ae/dachar/utils/switch_ds.py#L7-L15


def open_dset(dpath, force_repickle=False, **kwargs):

    open_kwargs = CONFIG["open_mfdataset_kwargs"].copy()
    open_kwargs.update(kwargs)

    fpattn = f"{dpath}/*.nc"
    logger.info(f"Reading: {fpattn}")

    pickle_path = _get_pickle_path(dpath)

    if os.path.isfile(pickle_path) and not force_repickle:
        try:
            with open(pickle_path, "rb") as reader:
               return pickle.load(reader)
        except Exception:
            # Assume failure so try to re-read and re-pickle the file
            pass

    ds = xr.open_mfdataset(fpattn, **open_kwargs)

    logger.info(f"Pickling dataset to: {pickle_path}")
    with open(pickle_path, 'wb') as writer:
        pkl = pickle.dump(ds, writer, protocol=-1)

    return ds
```

**Comment by agstephens** [comment]
This was some previous test code for demonstrating pickling was useful (faster):

```
import glob
import os
import xarray as xr
import time
import pickle

cache = 'dset_cache'
prefix = '/badc/cmip6/data'

if not os.path.isdir(cache):
    os.makedirs(cache)


def empty_cache():
    cache_files = glob.glob(f'{cache}/*.pkl')
    for f in cache_files:
        os.remove(f)


def time_it(func, *args, **kwargs):
    s = time.time()

    resp = func(*args, **kwargs)

    e = time.time()
    print(f'[INFO] Call to {func.__name__} with {args}, {kwargs}')
    print(f'       took: {e-s:.2f} seconds')

    return resp

def do():
    return None

time_it(do)


def path_to_dsid(dpath):
    return dpath.replace(prefix, '').strip('/').replace('/', '.')


def read_ds(dpath, use_cache=False, use_n_files=None):
    print(f'[INFO] Reading: {dpath}')

    dsid = path_to_dsid(dpath)
    pickle_path = f'{cache}/{dsid}.pkl'

    if use_cache:
        if os.path.isfile(pickle_path):
            with open(pickle_path, 'rb') as reader:
               return pickle.load(reader)

    dpaths = glob.glob(f'{dpath}/*.nc')[:use_n_files]
    print(f'[INFO] Reading from: {dpaths}')
    ds = xr.open_mfdataset(dpaths, use_cftime=True, combine="by_coords")

    with open(pickle_path, 'wb') as writer:
        pkl = pickle.dump(ds, writer, protocol=-1)

    return ds


def get_max_of_slice(ds, var_id):
    return float(ds[var_id].isel(time=slice(10, 50)).max())


def get_var_id(dpath):
    return path_to_dsid(dpath).split('.')[-3]


def main():
    dpath = '/badc/cmip6/data/CMIP6/HighResMIP/MIROC/NICAM16-9S/highresSST-present/r1i1p1f1/3hr/tos/gr/v20190830/'
    var_id = get_var_id(dpath)

    empty_cache()
    time_it(read_ds, dpath, {'use_cache': False, 'use_n_files': 3})

    ds = time_it(read_ds, dpath, {'use_cache': True, 'use_n_files': 3})
    mx = time_it(get_max_of_slice, ds, var_id)

    print(f'[INFO] Maximum value: {mx}')


if __name__ == '__main__':

    main()
```

**Comment by ellesmith88** [comment]
Done - all set up to publish to pypi, but not published yet as it seems we will have to take the pickling process out and do it somewhere else.

**Comment by agstephens** [comment]
Thanks @ellesmith88, why might we need to do it somewhere else?

**Comment by ellesmith88** [comment]
@agstephens  I think I was referring to what we discussed on Friday - that we can't use `open_dset` function as it is, because if the pickle doesn't exist it will won't be able to make it where we want it (under /badc/.../metadata/xarray-pickles/).

We said we would scan through and create the pickles, so I had thought we would remove this section:
https://github.com/cedadev/xarray-pickler/blob/56f73a5838f2fefaff6b36e5c1fd941984e12b4c/xarray_pickler/xarray_pickler.py#L66-L68

Was the idea to create the pickles beforehand but leave this in as well?

**Comment by ellesmith88** [comment]
Published to pypi https://pypi.org/project/xarray-pickler/0.1.0/

**Comment by agstephens** [comment]
Actually, `xarray-pickler` is likely to be superseded by https://grantjenks.com/docs/diskcache/ - as demonstrated in Carsten's notebook here:

https://github.com/roocs/rook/blob/dev-op-concat/notebooks/concat_with_cache.ipynb
